Repository actionhero/node-resque, pull requests merged in 2021-05, with the labels that each got.

#590 Bump hosted-git-info
  package-lock.json
Labels: dependencies

#594 Adding some high level documentation
  README.md
Labels: documentation

#596 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#595 Node.js v12 is required
  .nvmrc
  package-lock.json
  package.json
Labels: BREAKING-CHANGE, enhancement
